// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wrapping all messages
type GameMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GameMessage_AuthLogin
	//	*GameMessage_CharacterSelect
	//	*GameMessage_CharacterMove
	//	*GameMessage_CharacterMoveEnd
	//	*GameMessage_MapChangeRequest
	//	*GameMessage_Ping
	//	*GameMessage_AuthSuccess
	//	*GameMessage_CharacterInfo
	//	*GameMessage_MapData
	//	*GameMessage_MapActors
	//	*GameMessage_ActorAdd
	//	*GameMessage_ActorRemove
	//	*GameMessage_ActorMove
	//	*GameMessage_ActorUpdate
	//	*GameMessage_MapChangeResponse
	//	*GameMessage_Pong
	Msg           isGameMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetMsg() isGameMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GameMessage) GetAuthLogin() *AuthLogin {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_AuthLogin); ok {
			return x.AuthLogin
		}
	}
	return nil
}

func (x *GameMessage) GetCharacterSelect() *CharacterSelect {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_CharacterSelect); ok {
			return x.CharacterSelect
		}
	}
	return nil
}

func (x *GameMessage) GetCharacterMove() *CharacterMove {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_CharacterMove); ok {
			return x.CharacterMove
		}
	}
	return nil
}

func (x *GameMessage) GetCharacterMoveEnd() *CharacterMoveEnd {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_CharacterMoveEnd); ok {
			return x.CharacterMoveEnd
		}
	}
	return nil
}

func (x *GameMessage) GetMapChangeRequest() *MapChangeRequest {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_MapChangeRequest); ok {
			return x.MapChangeRequest
		}
	}
	return nil
}

func (x *GameMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *GameMessage) GetAuthSuccess() *AuthSuccess {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_AuthSuccess); ok {
			return x.AuthSuccess
		}
	}
	return nil
}

func (x *GameMessage) GetCharacterInfo() *CharacterInfo {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_CharacterInfo); ok {
			return x.CharacterInfo
		}
	}
	return nil
}

func (x *GameMessage) GetMapData() *MapData {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_MapData); ok {
			return x.MapData
		}
	}
	return nil
}

func (x *GameMessage) GetMapActors() *MapActors {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_MapActors); ok {
			return x.MapActors
		}
	}
	return nil
}

func (x *GameMessage) GetActorAdd() *ActorAdd {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_ActorAdd); ok {
			return x.ActorAdd
		}
	}
	return nil
}

func (x *GameMessage) GetActorRemove() *ActorRemove {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_ActorRemove); ok {
			return x.ActorRemove
		}
	}
	return nil
}

func (x *GameMessage) GetActorMove() *ActorMove {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_ActorMove); ok {
			return x.ActorMove
		}
	}
	return nil
}

func (x *GameMessage) GetActorUpdate() *ActorUpdate {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_ActorUpdate); ok {
			return x.ActorUpdate
		}
	}
	return nil
}

func (x *GameMessage) GetMapChangeResponse() *MapChangeResponse {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_MapChangeResponse); ok {
			return x.MapChangeResponse
		}
	}
	return nil
}

func (x *GameMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*GameMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isGameMessage_Msg interface {
	isGameMessage_Msg()
}

type GameMessage_AuthLogin struct {
	// Client -> Server
	AuthLogin *AuthLogin `protobuf:"bytes,1,opt,name=auth_login,json=authLogin,proto3,oneof"`
}

type GameMessage_CharacterSelect struct {
	CharacterSelect *CharacterSelect `protobuf:"bytes,2,opt,name=character_select,json=characterSelect,proto3,oneof"`
}

type GameMessage_CharacterMove struct {
	CharacterMove *CharacterMove `protobuf:"bytes,3,opt,name=character_move,json=characterMove,proto3,oneof"`
}

type GameMessage_CharacterMoveEnd struct {
	CharacterMoveEnd *CharacterMoveEnd `protobuf:"bytes,4,opt,name=character_move_end,json=characterMoveEnd,proto3,oneof"`
}

type GameMessage_MapChangeRequest struct {
	MapChangeRequest *MapChangeRequest `protobuf:"bytes,5,opt,name=map_change_request,json=mapChangeRequest,proto3,oneof"`
}

type GameMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

type GameMessage_AuthSuccess struct {
	// Server -> Client
	AuthSuccess *AuthSuccess `protobuf:"bytes,10,opt,name=auth_success,json=authSuccess,proto3,oneof"`
}

type GameMessage_CharacterInfo struct {
	CharacterInfo *CharacterInfo `protobuf:"bytes,11,opt,name=character_info,json=characterInfo,proto3,oneof"`
}

type GameMessage_MapData struct {
	MapData *MapData `protobuf:"bytes,20,opt,name=map_data,json=mapData,proto3,oneof"`
}

type GameMessage_MapActors struct {
	MapActors *MapActors `protobuf:"bytes,21,opt,name=map_actors,json=mapActors,proto3,oneof"`
}

type GameMessage_ActorAdd struct {
	ActorAdd *ActorAdd `protobuf:"bytes,30,opt,name=actor_add,json=actorAdd,proto3,oneof"`
}

type GameMessage_ActorRemove struct {
	ActorRemove *ActorRemove `protobuf:"bytes,31,opt,name=actor_remove,json=actorRemove,proto3,oneof"`
}

type GameMessage_ActorMove struct {
	ActorMove *ActorMove `protobuf:"bytes,32,opt,name=actor_move,json=actorMove,proto3,oneof"`
}

type GameMessage_ActorUpdate struct {
	ActorUpdate *ActorUpdate `protobuf:"bytes,33,opt,name=actor_update,json=actorUpdate,proto3,oneof"`
}

type GameMessage_MapChangeResponse struct {
	MapChangeResponse *MapChangeResponse `protobuf:"bytes,40,opt,name=map_change_response,json=mapChangeResponse,proto3,oneof"`
}

type GameMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,41,opt,name=pong,proto3,oneof"`
}

func (*GameMessage_AuthLogin) isGameMessage_Msg() {}

func (*GameMessage_CharacterSelect) isGameMessage_Msg() {}

func (*GameMessage_CharacterMove) isGameMessage_Msg() {}

func (*GameMessage_CharacterMoveEnd) isGameMessage_Msg() {}

func (*GameMessage_MapChangeRequest) isGameMessage_Msg() {}

func (*GameMessage_Ping) isGameMessage_Msg() {}

func (*GameMessage_AuthSuccess) isGameMessage_Msg() {}

func (*GameMessage_CharacterInfo) isGameMessage_Msg() {}

func (*GameMessage_MapData) isGameMessage_Msg() {}

func (*GameMessage_MapActors) isGameMessage_Msg() {}

func (*GameMessage_ActorAdd) isGameMessage_Msg() {}

func (*GameMessage_ActorRemove) isGameMessage_Msg() {}

func (*GameMessage_ActorMove) isGameMessage_Msg() {}

func (*GameMessage_ActorUpdate) isGameMessage_Msg() {}

func (*GameMessage_MapChangeResponse) isGameMessage_Msg() {}

func (*GameMessage_Pong) isGameMessage_Msg() {}

type AuthLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogin) Reset() {
	*x = AuthLogin{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogin) ProtoMessage() {}

func (x *AuthLogin) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogin.ProtoReflect.Descriptor instead.
func (*AuthLogin) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *AuthLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterSummary    `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSuccess) Reset() {
	*x = AuthSuccess{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSuccess) ProtoMessage() {}

func (x *AuthSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSuccess.ProtoReflect.Descriptor instead.
func (*AuthSuccess) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *AuthSuccess) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

type CharacterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gfx           int32                  `protobuf:"varint,3,opt,name=gfx,proto3" json:"gfx,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	MapId         int32                  `protobuf:"varint,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSummary) Reset() {
	*x = CharacterSummary{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSummary) ProtoMessage() {}

func (x *CharacterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSummary.ProtoReflect.Descriptor instead.
func (*CharacterSummary) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterSummary) GetGfx() int32 {
	if x != nil {
		return x.Gfx
	}
	return 0
}

func (x *CharacterSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterSummary) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type CharacterSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSelect) Reset() {
	*x = CharacterSelect{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSelect) ProtoMessage() {}

func (x *CharacterSelect) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSelect.ProtoReflect.Descriptor instead.
func (*CharacterSelect) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterSelect) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gfx           int32                  `protobuf:"varint,3,opt,name=gfx,proto3" json:"gfx,omitempty"`
	MapId         int32                  `protobuf:"varint,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	CellId        int32                  `protobuf:"varint,5,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Direction     int32                  `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Color1        int32                  `protobuf:"varint,7,opt,name=color1,proto3" json:"color1,omitempty"`
	Color2        int32                  `protobuf:"varint,8,opt,name=color2,proto3" json:"color2,omitempty"`
	Color3        int32                  `protobuf:"varint,9,opt,name=color3,proto3" json:"color3,omitempty"`
	Look          string                 `protobuf:"bytes,10,opt,name=look,proto3" json:"look,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterInfo) GetGfx() int32 {
	if x != nil {
		return x.Gfx
	}
	return 0
}

func (x *CharacterInfo) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CharacterInfo) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *CharacterInfo) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *CharacterInfo) GetColor1() int32 {
	if x != nil {
		return x.Color1
	}
	return 0
}

func (x *CharacterInfo) GetColor2() int32 {
	if x != nil {
		return x.Color2
	}
	return 0
}

func (x *CharacterInfo) GetColor3() int32 {
	if x != nil {
		return x.Color3
	}
	return 0
}

func (x *CharacterInfo) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         int32                  `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Background    int32                  `protobuf:"varint,4,opt,name=background,proto3" json:"background,omitempty"`
	Cells         []*CellData            `protobuf:"bytes,5,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *MapData) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapData) GetBackground() int32 {
	if x != nil {
		return x.Background
	}
	return 0
}

func (x *MapData) GetCells() []*CellData {
	if x != nil {
		return x.Cells
	}
	return nil
}

type CellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Ground        int32                  `protobuf:"varint,3,opt,name=ground,proto3" json:"ground,omitempty"`
	Layer1        int32                  `protobuf:"varint,4,opt,name=layer1,proto3" json:"layer1,omitempty"`
	Layer2        int32                  `protobuf:"varint,5,opt,name=layer2,proto3" json:"layer2,omitempty"`
	GroundLevel   int32                  `protobuf:"varint,6,opt,name=ground_level,json=groundLevel,proto3" json:"ground_level,omitempty"`
	Walkable      bool                   `protobuf:"varint,7,opt,name=walkable,proto3" json:"walkable,omitempty"`
	Movement      int32                  `protobuf:"varint,8,opt,name=movement,proto3" json:"movement,omitempty"`
	LineOfSight   bool                   `protobuf:"varint,9,opt,name=line_of_sight,json=lineOfSight,proto3" json:"line_of_sight,omitempty"`
	GroundSlope   int32                  `protobuf:"varint,10,opt,name=ground_slope,json=groundSlope,proto3" json:"ground_slope,omitempty"`
	GroundRot     int32                  `protobuf:"varint,11,opt,name=ground_rot,json=groundRot,proto3" json:"ground_rot,omitempty"`
	GroundFlip    bool                   `protobuf:"varint,12,opt,name=ground_flip,json=groundFlip,proto3" json:"ground_flip,omitempty"`
	Obj1Rot       int32                  `protobuf:"varint,13,opt,name=obj1_rot,json=obj1Rot,proto3" json:"obj1_rot,omitempty"`
	Obj1Flip      bool                   `protobuf:"varint,14,opt,name=obj1_flip,json=obj1Flip,proto3" json:"obj1_flip,omitempty"`
	Obj2Rot       int32                  `protobuf:"varint,15,opt,name=obj2_rot,json=obj2Rot,proto3" json:"obj2_rot,omitempty"`
	Obj2Flip      bool                   `protobuf:"varint,16,opt,name=obj2_flip,json=obj2Flip,proto3" json:"obj2_flip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellData) Reset() {
	*x = CellData{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellData) ProtoMessage() {}

func (x *CellData) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellData.ProtoReflect.Descriptor instead.
func (*CellData) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *CellData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CellData) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CellData) GetGround() int32 {
	if x != nil {
		return x.Ground
	}
	return 0
}

func (x *CellData) GetLayer1() int32 {
	if x != nil {
		return x.Layer1
	}
	return 0
}

func (x *CellData) GetLayer2() int32 {
	if x != nil {
		return x.Layer2
	}
	return 0
}

func (x *CellData) GetGroundLevel() int32 {
	if x != nil {
		return x.GroundLevel
	}
	return 0
}

func (x *CellData) GetWalkable() bool {
	if x != nil {
		return x.Walkable
	}
	return false
}

func (x *CellData) GetMovement() int32 {
	if x != nil {
		return x.Movement
	}
	return 0
}

func (x *CellData) GetLineOfSight() bool {
	if x != nil {
		return x.LineOfSight
	}
	return false
}

func (x *CellData) GetGroundSlope() int32 {
	if x != nil {
		return x.GroundSlope
	}
	return 0
}

func (x *CellData) GetGroundRot() int32 {
	if x != nil {
		return x.GroundRot
	}
	return 0
}

func (x *CellData) GetGroundFlip() bool {
	if x != nil {
		return x.GroundFlip
	}
	return false
}

func (x *CellData) GetObj1Rot() int32 {
	if x != nil {
		return x.Obj1Rot
	}
	return 0
}

func (x *CellData) GetObj1Flip() bool {
	if x != nil {
		return x.Obj1Flip
	}
	return false
}

func (x *CellData) GetObj2Rot() int32 {
	if x != nil {
		return x.Obj2Rot
	}
	return 0
}

func (x *CellData) GetObj2Flip() bool {
	if x != nil {
		return x.Obj2Flip
	}
	return false
}

type MapActors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*ActorInfo           `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapActors) Reset() {
	*x = MapActors{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapActors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapActors) ProtoMessage() {}

func (x *MapActors) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapActors.ProtoReflect.Descriptor instead.
func (*MapActors) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *MapActors) GetActors() []*ActorInfo {
	if x != nil {
		return x.Actors
	}
	return nil
}

type ActorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CellId        int32                  `protobuf:"varint,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Direction     int32                  `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Look          string                 `protobuf:"bytes,5,opt,name=look,proto3" json:"look,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorInfo) Reset() {
	*x = ActorInfo{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorInfo) ProtoMessage() {}

func (x *ActorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorInfo.ProtoReflect.Descriptor instead.
func (*ActorInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *ActorInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActorInfo) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *ActorInfo) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *ActorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorInfo) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

type ActorAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CellId        int32                  `protobuf:"varint,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Direction     int32                  `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Look          string                 `protobuf:"bytes,5,opt,name=look,proto3" json:"look,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorAdd) Reset() {
	*x = ActorAdd{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorAdd) ProtoMessage() {}

func (x *ActorAdd) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorAdd.ProtoReflect.Descriptor instead.
func (*ActorAdd) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *ActorAdd) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActorAdd) GetCellId() int32 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *ActorAdd) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *ActorAdd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorAdd) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

type ActorRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRemove) Reset() {
	*x = ActorRemove{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRemove) ProtoMessage() {}

func (x *ActorRemove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRemove.ProtoReflect.Descriptor instead.
func (*ActorRemove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *ActorRemove) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActorMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          []int32                `protobuf:"varint,2,rep,packed,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorMove) Reset() {
	*x = ActorMove{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorMove) ProtoMessage() {}

func (x *ActorMove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorMove.ProtoReflect.Descriptor instead.
func (*ActorMove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *ActorMove) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActorMove) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

type ActorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Look          string                 `protobuf:"bytes,2,opt,name=look,proto3" json:"look,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorUpdate) Reset() {
	*x = ActorUpdate{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorUpdate) ProtoMessage() {}

func (x *ActorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorUpdate.ProtoReflect.Descriptor instead.
func (*ActorUpdate) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *ActorUpdate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActorUpdate) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

type CharacterMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []int32                `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMove) Reset() {
	*x = CharacterMove{}
	mi := &file_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMove) ProtoMessage() {}

func (x *CharacterMove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMove.ProtoReflect.Descriptor instead.
func (*CharacterMove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *CharacterMove) GetPath() []int32 {
	if x != nil {
		return x.Path
	}
	return nil
}

type CharacterMoveEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMoveEnd) Reset() {
	*x = CharacterMoveEnd{}
	mi := &file_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMoveEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMoveEnd) ProtoMessage() {}

func (x *CharacterMoveEnd) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMoveEnd.ProtoReflect.Descriptor instead.
func (*CharacterMoveEnd) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

type MapChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetMapId   int32                  `protobuf:"varint,1,opt,name=target_map_id,json=targetMapId,proto3" json:"target_map_id,omitempty"`
	TargetCellId  int32                  `protobuf:"varint,2,opt,name=target_cell_id,json=targetCellId,proto3" json:"target_cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangeRequest) Reset() {
	*x = MapChangeRequest{}
	mi := &file_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangeRequest) ProtoMessage() {}

func (x *MapChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangeRequest.ProtoReflect.Descriptor instead.
func (*MapChangeRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

func (x *MapChangeRequest) GetTargetMapId() int32 {
	if x != nil {
		return x.TargetMapId
	}
	return 0
}

func (x *MapChangeRequest) GetTargetCellId() int32 {
	if x != nil {
		return x.TargetCellId
	}
	return 0
}

type MapChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         int32                  `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangeResponse) Reset() {
	*x = MapChangeResponse{}
	mi := &file_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangeResponse) ProtoMessage() {}

func (x *MapChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangeResponse.ProtoReflect.Descriptor instead.
func (*MapChangeResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17}
}

func (x *MapChangeResponse) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{19}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x05dofus\"\x9c\a\n" +
	"\vGameMessage\x121\n" +
	"\n" +
	"auth_login\x18\x01 \x01(\v2\x10.dofus.AuthLoginH\x00R\tauthLogin\x12C\n" +
	"\x10character_select\x18\x02 \x01(\v2\x16.dofus.CharacterSelectH\x00R\x0fcharacterSelect\x12=\n" +
	"\x0echaracter_move\x18\x03 \x01(\v2\x14.dofus.CharacterMoveH\x00R\rcharacterMove\x12G\n" +
	"\x12character_move_end\x18\x04 \x01(\v2\x17.dofus.CharacterMoveEndH\x00R\x10characterMoveEnd\x12G\n" +
	"\x12map_change_request\x18\x05 \x01(\v2\x17.dofus.MapChangeRequestH\x00R\x10mapChangeRequest\x12!\n" +
	"\x04ping\x18\x06 \x01(\v2\v.dofus.PingH\x00R\x04ping\x127\n" +
	"\fauth_success\x18\n" +
	" \x01(\v2\x12.dofus.AuthSuccessH\x00R\vauthSuccess\x12=\n" +
	"\x0echaracter_info\x18\v \x01(\v2\x14.dofus.CharacterInfoH\x00R\rcharacterInfo\x12+\n" +
	"\bmap_data\x18\x14 \x01(\v2\x0e.dofus.MapDataH\x00R\amapData\x121\n" +
	"\n" +
	"map_actors\x18\x15 \x01(\v2\x10.dofus.MapActorsH\x00R\tmapActors\x12.\n" +
	"\tactor_add\x18\x1e \x01(\v2\x0f.dofus.ActorAddH\x00R\bactorAdd\x127\n" +
	"\factor_remove\x18\x1f \x01(\v2\x12.dofus.ActorRemoveH\x00R\vactorRemove\x121\n" +
	"\n" +
	"actor_move\x18  \x01(\v2\x10.dofus.ActorMoveH\x00R\tactorMove\x127\n" +
	"\factor_update\x18! \x01(\v2\x12.dofus.ActorUpdateH\x00R\vactorUpdate\x12J\n" +
	"\x13map_change_response\x18( \x01(\v2\x18.dofus.MapChangeResponseH\x00R\x11mapChangeResponse\x12!\n" +
	"\x04pong\x18) \x01(\v2\v.dofus.PongH\x00R\x04pongB\x05\n" +
	"\x03msg\"C\n" +
	"\tAuthLogin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\vAuthSuccess\x127\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x17.dofus.CharacterSummaryR\n" +
	"characters\"u\n" +
	"\x10CharacterSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03gfx\x18\x03 \x01(\x05R\x03gfx\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x15\n" +
	"\x06map_id\x18\x05 \x01(\x05R\x05mapId\"4\n" +
	"\x0fCharacterSelect\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\"\xef\x01\n" +
	"\rCharacterInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03gfx\x18\x03 \x01(\x05R\x03gfx\x12\x15\n" +
	"\x06map_id\x18\x04 \x01(\x05R\x05mapId\x12\x17\n" +
	"\acell_id\x18\x05 \x01(\x05R\x06cellId\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\x05R\tdirection\x12\x16\n" +
	"\x06color1\x18\a \x01(\x05R\x06color1\x12\x16\n" +
	"\x06color2\x18\b \x01(\x05R\x06color2\x12\x16\n" +
	"\x06color3\x18\t \x01(\x05R\x06color3\x12\x12\n" +
	"\x04look\x18\n" +
	" \x01(\tR\x04look\"\x95\x01\n" +
	"\aMapData\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\x05R\x05mapId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"background\x18\x04 \x01(\x05R\n" +
	"background\x12%\n" +
	"\x05cells\x18\x05 \x03(\v2\x0f.dofus.CellDataR\x05cells\"\xcc\x03\n" +
	"\bCellData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x16\n" +
	"\x06ground\x18\x03 \x01(\x05R\x06ground\x12\x16\n" +
	"\x06layer1\x18\x04 \x01(\x05R\x06layer1\x12\x16\n" +
	"\x06layer2\x18\x05 \x01(\x05R\x06layer2\x12!\n" +
	"\fground_level\x18\x06 \x01(\x05R\vgroundLevel\x12\x1a\n" +
	"\bwalkable\x18\a \x01(\bR\bwalkable\x12\x1a\n" +
	"\bmovement\x18\b \x01(\x05R\bmovement\x12\"\n" +
	"\rline_of_sight\x18\t \x01(\bR\vlineOfSight\x12!\n" +
	"\fground_slope\x18\n" +
	" \x01(\x05R\vgroundSlope\x12\x1d\n" +
	"\n" +
	"ground_rot\x18\v \x01(\x05R\tgroundRot\x12\x1f\n" +
	"\vground_flip\x18\f \x01(\bR\n" +
	"groundFlip\x12\x19\n" +
	"\bobj1_rot\x18\r \x01(\x05R\aobj1Rot\x12\x1b\n" +
	"\tobj1_flip\x18\x0e \x01(\bR\bobj1Flip\x12\x19\n" +
	"\bobj2_rot\x18\x0f \x01(\x05R\aobj2Rot\x12\x1b\n" +
	"\tobj2_flip\x18\x10 \x01(\bR\bobj2Flip\"5\n" +
	"\tMapActors\x12(\n" +
	"\x06actors\x18\x01 \x03(\v2\x10.dofus.ActorInfoR\x06actors\"z\n" +
	"\tActorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\x05R\x06cellId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04look\x18\x05 \x01(\tR\x04look\"y\n" +
	"\bActorAdd\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\x05R\x06cellId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04look\x18\x05 \x01(\tR\x04look\"\x1d\n" +
	"\vActorRemove\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\tActorMove\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x03(\x05R\x04path\"1\n" +
	"\vActorUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04look\x18\x02 \x01(\tR\x04look\"#\n" +
	"\rCharacterMove\x12\x12\n" +
	"\x04path\x18\x01 \x03(\x05R\x04path\"\x12\n" +
	"\x10CharacterMoveEnd\"\\\n" +
	"\x10MapChangeRequest\x12\"\n" +
	"\rtarget_map_id\x18\x01 \x01(\x05R\vtargetMapId\x12$\n" +
	"\x0etarget_cell_id\x18\x02 \x01(\x05R\ftargetCellId\"*\n" +
	"\x11MapChangeResponse\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\x05R\x05mapId\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestampB6Z\x1bdofus-server/internal/proto\xaa\x02\x16DofusRetroFuture.Protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_game_proto_goTypes = []any{
	(*GameMessage)(nil),       // 0: dofus.GameMessage
	(*AuthLogin)(nil),         // 1: dofus.AuthLogin
	(*AuthSuccess)(nil),       // 2: dofus.AuthSuccess
	(*CharacterSummary)(nil),  // 3: dofus.CharacterSummary
	(*CharacterSelect)(nil),   // 4: dofus.CharacterSelect
	(*CharacterInfo)(nil),     // 5: dofus.CharacterInfo
	(*MapData)(nil),           // 6: dofus.MapData
	(*CellData)(nil),          // 7: dofus.CellData
	(*MapActors)(nil),         // 8: dofus.MapActors
	(*ActorInfo)(nil),         // 9: dofus.ActorInfo
	(*ActorAdd)(nil),          // 10: dofus.ActorAdd
	(*ActorRemove)(nil),       // 11: dofus.ActorRemove
	(*ActorMove)(nil),         // 12: dofus.ActorMove
	(*ActorUpdate)(nil),       // 13: dofus.ActorUpdate
	(*CharacterMove)(nil),     // 14: dofus.CharacterMove
	(*CharacterMoveEnd)(nil),  // 15: dofus.CharacterMoveEnd
	(*MapChangeRequest)(nil),  // 16: dofus.MapChangeRequest
	(*MapChangeResponse)(nil), // 17: dofus.MapChangeResponse
	(*Ping)(nil),              // 18: dofus.Ping
	(*Pong)(nil),              // 19: dofus.Pong
}
var file_game_proto_depIdxs = []int32{
	1,  // 0: dofus.GameMessage.auth_login:type_name -> dofus.AuthLogin
	4,  // 1: dofus.GameMessage.character_select:type_name -> dofus.CharacterSelect
	14, // 2: dofus.GameMessage.character_move:type_name -> dofus.CharacterMove
	15, // 3: dofus.GameMessage.character_move_end:type_name -> dofus.CharacterMoveEnd
	16, // 4: dofus.GameMessage.map_change_request:type_name -> dofus.MapChangeRequest
	18, // 5: dofus.GameMessage.ping:type_name -> dofus.Ping
	2,  // 6: dofus.GameMessage.auth_success:type_name -> dofus.AuthSuccess
	5,  // 7: dofus.GameMessage.character_info:type_name -> dofus.CharacterInfo
	6,  // 8: dofus.GameMessage.map_data:type_name -> dofus.MapData
	8,  // 9: dofus.GameMessage.map_actors:type_name -> dofus.MapActors
	10, // 10: dofus.GameMessage.actor_add:type_name -> dofus.ActorAdd
	11, // 11: dofus.GameMessage.actor_remove:type_name -> dofus.ActorRemove
	12, // 12: dofus.GameMessage.actor_move:type_name -> dofus.ActorMove
	13, // 13: dofus.GameMessage.actor_update:type_name -> dofus.ActorUpdate
	17, // 14: dofus.GameMessage.map_change_response:type_name -> dofus.MapChangeResponse
	19, // 15: dofus.GameMessage.pong:type_name -> dofus.Pong
	3,  // 16: dofus.AuthSuccess.characters:type_name -> dofus.CharacterSummary
	7,  // 17: dofus.MapData.cells:type_name -> dofus.CellData
	9,  // 18: dofus.MapActors.actors:type_name -> dofus.ActorInfo
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[0].OneofWrappers = []any{
		(*GameMessage_AuthLogin)(nil),
		(*GameMessage_CharacterSelect)(nil),
		(*GameMessage_CharacterMove)(nil),
		(*GameMessage_CharacterMoveEnd)(nil),
		(*GameMessage_MapChangeRequest)(nil),
		(*GameMessage_Ping)(nil),
		(*GameMessage_AuthSuccess)(nil),
		(*GameMessage_CharacterInfo)(nil),
		(*GameMessage_MapData)(nil),
		(*GameMessage_MapActors)(nil),
		(*GameMessage_ActorAdd)(nil),
		(*GameMessage_ActorRemove)(nil),
		(*GameMessage_ActorMove)(nil),
		(*GameMessage_ActorUpdate)(nil),
		(*GameMessage_MapChangeResponse)(nil),
		(*GameMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
