// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (account_id, name, class, sex, gfx, color1, color2, color3)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateCharacterParams struct {
	AccountID int32       `json:"account_id"`
	Name      string      `json:"name"`
	Class     int16       `json:"class"`
	Sex       int16       `json:"sex"`
	Gfx       int32       `json:"gfx"`
	Color1    pgtype.Int4 `json:"color1"`
	Color2    pgtype.Int4 `json:"color2"`
	Color3    pgtype.Int4 `json:"color3"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.AccountID,
		arg.Name,
		arg.Class,
		arg.Sex,
		arg.Gfx,
		arg.Color1,
		arg.Color2,
		arg.Color3,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getCharacterByID = `-- name: GetCharacterByID :one
SELECT id, account_id, name, class, sex, color1, color2, color3, gfx, level,
       map_id, cell_id, direction, vitality, wisdom, strength, chance, agility, intelligence,
       hp, max_hp, ap, mp, xp, xp_low, xp_high, kama
FROM characters
WHERE id = $1
`

type GetCharacterByIDRow struct {
	ID           int32       `json:"id"`
	AccountID    int32       `json:"account_id"`
	Name         string      `json:"name"`
	Class        int16       `json:"class"`
	Sex          int16       `json:"sex"`
	Color1       pgtype.Int4 `json:"color1"`
	Color2       pgtype.Int4 `json:"color2"`
	Color3       pgtype.Int4 `json:"color3"`
	Gfx          int32       `json:"gfx"`
	Level        pgtype.Int4 `json:"level"`
	MapID        pgtype.Int4 `json:"map_id"`
	CellID       pgtype.Int4 `json:"cell_id"`
	Direction    pgtype.Int2 `json:"direction"`
	Vitality     pgtype.Int4 `json:"vitality"`
	Wisdom       pgtype.Int4 `json:"wisdom"`
	Strength     pgtype.Int4 `json:"strength"`
	Chance       pgtype.Int4 `json:"chance"`
	Agility      pgtype.Int4 `json:"agility"`
	Intelligence pgtype.Int4 `json:"intelligence"`
	Hp           pgtype.Int4 `json:"hp"`
	MaxHp        pgtype.Int4 `json:"max_hp"`
	Ap           pgtype.Int2 `json:"ap"`
	Mp           pgtype.Int2 `json:"mp"`
	Xp           pgtype.Int8 `json:"xp"`
	XpLow        pgtype.Int8 `json:"xp_low"`
	XpHigh       pgtype.Int8 `json:"xp_high"`
	Kama         pgtype.Int4 `json:"kama"`
}

func (q *Queries) GetCharacterByID(ctx context.Context, id int32) (GetCharacterByIDRow, error) {
	row := q.db.QueryRow(ctx, getCharacterByID, id)
	var i GetCharacterByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Class,
		&i.Sex,
		&i.Color1,
		&i.Color2,
		&i.Color3,
		&i.Gfx,
		&i.Level,
		&i.MapID,
		&i.CellID,
		&i.Direction,
		&i.Vitality,
		&i.Wisdom,
		&i.Strength,
		&i.Chance,
		&i.Agility,
		&i.Intelligence,
		&i.Hp,
		&i.MaxHp,
		&i.Ap,
		&i.Mp,
		&i.Xp,
		&i.XpLow,
		&i.XpHigh,
		&i.Kama,
	)
	return i, err
}

const getCharactersByAccountID = `-- name: GetCharactersByAccountID :many
SELECT id, account_id, name, class, sex, color1, color2, color3, gfx, level, map_id, cell_id, direction
FROM characters
WHERE account_id = $1
`

type GetCharactersByAccountIDRow struct {
	ID        int32       `json:"id"`
	AccountID int32       `json:"account_id"`
	Name      string      `json:"name"`
	Class     int16       `json:"class"`
	Sex       int16       `json:"sex"`
	Color1    pgtype.Int4 `json:"color1"`
	Color2    pgtype.Int4 `json:"color2"`
	Color3    pgtype.Int4 `json:"color3"`
	Gfx       int32       `json:"gfx"`
	Level     pgtype.Int4 `json:"level"`
	MapID     pgtype.Int4 `json:"map_id"`
	CellID    pgtype.Int4 `json:"cell_id"`
	Direction pgtype.Int2 `json:"direction"`
}

func (q *Queries) GetCharactersByAccountID(ctx context.Context, accountID int32) ([]GetCharactersByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getCharactersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCharactersByAccountIDRow{}
	for rows.Next() {
		var i GetCharactersByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Class,
			&i.Sex,
			&i.Color1,
			&i.Color2,
			&i.Color3,
			&i.Gfx,
			&i.Level,
			&i.MapID,
			&i.CellID,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterPosition = `-- name: UpdateCharacterPosition :exec
UPDATE characters
SET map_id = $2, cell_id = $3, direction = $4
WHERE id = $1
`

type UpdateCharacterPositionParams struct {
	ID        int32       `json:"id"`
	MapID     pgtype.Int4 `json:"map_id"`
	CellID    pgtype.Int4 `json:"cell_id"`
	Direction pgtype.Int2 `json:"direction"`
}

func (q *Queries) UpdateCharacterPosition(ctx context.Context, arg UpdateCharacterPositionParams) error {
	_, err := q.db.Exec(ctx, updateCharacterPosition,
		arg.ID,
		arg.MapID,
		arg.CellID,
		arg.Direction,
	)
	return err
}
