// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCharacterItem = `-- name: AddCharacterItem :one
INSERT INTO character_items (character_id, template_id, quantity, position, effects)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type AddCharacterItemParams struct {
	CharacterID int32       `json:"character_id"`
	TemplateID  int32       `json:"template_id"`
	Quantity    pgtype.Int4 `json:"quantity"`
	Position    pgtype.Int2 `json:"position"`
	Effects     []byte      `json:"effects"`
}

func (q *Queries) AddCharacterItem(ctx context.Context, arg AddCharacterItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, addCharacterItem,
		arg.CharacterID,
		arg.TemplateID,
		arg.Quantity,
		arg.Position,
		arg.Effects,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCharacterItem = `-- name: DeleteCharacterItem :exec
DELETE FROM character_items WHERE id = $1
`

func (q *Queries) DeleteCharacterItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCharacterItem, id)
	return err
}

const getCharacterItems = `-- name: GetCharacterItems :many
SELECT ci.id, ci.character_id, ci.template_id, ci.quantity, ci.position, ci.effects,
       it.name, it.type, it.gfx_id, it.weight, it.equip_positions
FROM character_items ci
JOIN item_templates it ON ci.template_id = it.id
WHERE ci.character_id = $1
`

type GetCharacterItemsRow struct {
	ID             int32       `json:"id"`
	CharacterID    int32       `json:"character_id"`
	TemplateID     int32       `json:"template_id"`
	Quantity       pgtype.Int4 `json:"quantity"`
	Position       pgtype.Int2 `json:"position"`
	Effects        []byte      `json:"effects"`
	Name           string      `json:"name"`
	Type           int16       `json:"type"`
	GfxID          pgtype.Int4 `json:"gfx_id"`
	Weight         pgtype.Int4 `json:"weight"`
	EquipPositions []byte      `json:"equip_positions"`
}

func (q *Queries) GetCharacterItems(ctx context.Context, characterID int32) ([]GetCharacterItemsRow, error) {
	rows, err := q.db.Query(ctx, getCharacterItems, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCharacterItemsRow{}
	for rows.Next() {
		var i GetCharacterItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.TemplateID,
			&i.Quantity,
			&i.Position,
			&i.Effects,
			&i.Name,
			&i.Type,
			&i.GfxID,
			&i.Weight,
			&i.EquipPositions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemTemplate = `-- name: GetItemTemplate :one
SELECT id, name, type, super_type, level, gfx_id, description, weight,
       equip_positions, two_handed, effects, item_set_id, usable, stackable
FROM item_templates
WHERE id = $1
`

func (q *Queries) GetItemTemplate(ctx context.Context, id int32) (ItemTemplate, error) {
	row := q.db.QueryRow(ctx, getItemTemplate, id)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.SuperType,
		&i.Level,
		&i.GfxID,
		&i.Description,
		&i.Weight,
		&i.EquipPositions,
		&i.TwoHanded,
		&i.Effects,
		&i.ItemSetID,
		&i.Usable,
		&i.Stackable,
	)
	return i, err
}

const updateCharacterItemPosition = `-- name: UpdateCharacterItemPosition :exec
UPDATE character_items SET position = $2 WHERE id = $1
`

type UpdateCharacterItemPositionParams struct {
	ID       int32       `json:"id"`
	Position pgtype.Int2 `json:"position"`
}

func (q *Queries) UpdateCharacterItemPosition(ctx context.Context, arg UpdateCharacterItemPositionParams) error {
	_, err := q.db.Exec(ctx, updateCharacterItemPosition, arg.ID, arg.Position)
	return err
}

const updateCharacterItemQuantity = `-- name: UpdateCharacterItemQuantity :exec
UPDATE character_items SET quantity = $2 WHERE id = $1
`

type UpdateCharacterItemQuantityParams struct {
	ID       int32       `json:"id"`
	Quantity pgtype.Int4 `json:"quantity"`
}

func (q *Queries) UpdateCharacterItemQuantity(ctx context.Context, arg UpdateCharacterItemQuantityParams) error {
	_, err := q.db.Exec(ctx, updateCharacterItemQuantity, arg.ID, arg.Quantity)
	return err
}
