// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdjacentMaps = `-- name: GetAdjacentMaps :many
SELECT id, x, y
FROM maps
WHERE superarea = $1 AND (
    (x = $2 + 1 AND y = $3) OR
    (x = $2 - 1 AND y = $3) OR
    (x = $2 AND y = $3 + 1) OR
    (x = $2 AND y = $3 - 1)
)
`

type GetAdjacentMapsParams struct {
	Superarea int32       `json:"superarea"`
	Column2   interface{} `json:"column_2"`
	Y         int32       `json:"y"`
}

type GetAdjacentMapsRow struct {
	ID int32 `json:"id"`
	X  int32 `json:"x"`
	Y  int32 `json:"y"`
}

func (q *Queries) GetAdjacentMaps(ctx context.Context, arg GetAdjacentMapsParams) ([]GetAdjacentMapsRow, error) {
	rows, err := q.db.Query(ctx, getAdjacentMaps, arg.Superarea, arg.Column2, arg.Y)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdjacentMapsRow{}
	for rows.Next() {
		var i GetAdjacentMapsRow
		if err := rows.Scan(&i.ID, &i.X, &i.Y); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMapByID = `-- name: GetMapByID :one
SELECT id, width, height, x, y, superarea, background, cells_gzip, walkable_ids
FROM maps
WHERE id = $1
`

type GetMapByIDRow struct {
	ID          int32       `json:"id"`
	Width       int32       `json:"width"`
	Height      int32       `json:"height"`
	X           int32       `json:"x"`
	Y           int32       `json:"y"`
	Superarea   int32       `json:"superarea"`
	Background  pgtype.Int4 `json:"background"`
	CellsGzip   []byte      `json:"cells_gzip"`
	WalkableIds []int32     `json:"walkable_ids"`
}

func (q *Queries) GetMapByID(ctx context.Context, id int32) (GetMapByIDRow, error) {
	row := q.db.QueryRow(ctx, getMapByID, id)
	var i GetMapByIDRow
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.X,
		&i.Y,
		&i.Superarea,
		&i.Background,
		&i.CellsGzip,
		&i.WalkableIds,
	)
	return i, err
}

const getScriptedCellsByMapID = `-- name: GetScriptedCellsByMapID :many
SELECT map_id, cell_id, action_id, event_id, action_args, conditions
FROM scripted_cells
WHERE map_id = $1
`

func (q *Queries) GetScriptedCellsByMapID(ctx context.Context, mapID int32) ([]ScriptedCell, error) {
	rows, err := q.db.Query(ctx, getScriptedCellsByMapID, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScriptedCell{}
	for rows.Next() {
		var i ScriptedCell
		if err := rows.Scan(
			&i.MapID,
			&i.CellID,
			&i.ActionID,
			&i.EventID,
			&i.ActionArgs,
			&i.Conditions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
