// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Pseudo   string `json:"pseudo"`
}

type Character struct {
	ID               int32       `json:"id"`
	AccountID        int32       `json:"account_id"`
	Name             string      `json:"name"`
	Class            int16       `json:"class"`
	Sex              int16       `json:"sex"`
	Color1           pgtype.Int4 `json:"color1"`
	Color2           pgtype.Int4 `json:"color2"`
	Color3           pgtype.Int4 `json:"color3"`
	Gfx              int32       `json:"gfx"`
	Level            pgtype.Int4 `json:"level"`
	MapID            pgtype.Int4 `json:"map_id"`
	CellID           pgtype.Int4 `json:"cell_id"`
	Direction        pgtype.Int2 `json:"direction"`
	Vitality         pgtype.Int4 `json:"vitality"`
	Wisdom           pgtype.Int4 `json:"wisdom"`
	Strength         pgtype.Int4 `json:"strength"`
	Chance           pgtype.Int4 `json:"chance"`
	Agility          pgtype.Int4 `json:"agility"`
	Intelligence     pgtype.Int4 `json:"intelligence"`
	Hp               pgtype.Int4 `json:"hp"`
	MaxHp            pgtype.Int4 `json:"max_hp"`
	Ap               pgtype.Int2 `json:"ap"`
	Mp               pgtype.Int2 `json:"mp"`
	Initiative       pgtype.Int4 `json:"initiative"`
	Discernment      pgtype.Int4 `json:"discernment"`
	Range            pgtype.Int2 `json:"range"`
	SummonLimit      pgtype.Int2 `json:"summon_limit"`
	Energy           pgtype.Int4 `json:"energy"`
	MaxEnergy        pgtype.Int4 `json:"max_energy"`
	BonusPoints      pgtype.Int4 `json:"bonus_points"`
	BonusPointsSpell pgtype.Int4 `json:"bonus_points_spell"`
	Xp               pgtype.Int8 `json:"xp"`
	XpLow            pgtype.Int8 `json:"xp_low"`
	XpHigh           pgtype.Int8 `json:"xp_high"`
	Kama             pgtype.Int4 `json:"kama"`
}

type CharacterItem struct {
	ID          int32       `json:"id"`
	CharacterID int32       `json:"character_id"`
	TemplateID  int32       `json:"template_id"`
	Quantity    pgtype.Int4 `json:"quantity"`
	Position    pgtype.Int2 `json:"position"`
	Effects     []byte      `json:"effects"`
}

type ItemTemplate struct {
	ID             int32       `json:"id"`
	Name           string      `json:"name"`
	Type           int16       `json:"type"`
	SuperType      pgtype.Int2 `json:"super_type"`
	Level          pgtype.Int2 `json:"level"`
	GfxID          pgtype.Int4 `json:"gfx_id"`
	Description    pgtype.Text `json:"description"`
	Weight         pgtype.Int4 `json:"weight"`
	EquipPositions []byte      `json:"equip_positions"`
	TwoHanded      pgtype.Bool `json:"two_handed"`
	Effects        []byte      `json:"effects"`
	ItemSetID      pgtype.Int4 `json:"item_set_id"`
	Usable         pgtype.Bool `json:"usable"`
	Stackable      pgtype.Bool `json:"stackable"`
}

type Map struct {
	ID          int32       `json:"id"`
	Width       int32       `json:"width"`
	Height      int32       `json:"height"`
	X           int32       `json:"x"`
	Y           int32       `json:"y"`
	Superarea   int32       `json:"superarea"`
	Background  pgtype.Int4 `json:"background"`
	Places      pgtype.Text `json:"places"`
	Cells       []byte      `json:"cells"`
	CellsGzip   []byte      `json:"cells_gzip"`
	WalkableIds []int32     `json:"walkable_ids"`
	Monsters    pgtype.Text `json:"monsters"`
}

type ScriptedCell struct {
	MapID      int32       `json:"map_id"`
	CellID     int32       `json:"cell_id"`
	ActionID   int32       `json:"action_id"`
	EventID    int32       `json:"event_id"`
	ActionArgs pgtype.Text `json:"action_args"`
	Conditions pgtype.Text `json:"conditions"`
}
