[package]
name = "dofus-vello-godot"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
dofasset-renderer = { path = "dofasset-renderer" }
vello = "0.8"
wgpu = { version = "28", features = ["metal", "vulkan", "dx12"] }
wgpu-hal = { version = "28", features = ["dx12"] }
pollster = "0.4"
ash = "0.38"

[target.'cfg(target_vendor = "apple")'.dependencies]
metal = "0.33"
